import type { CommandDefinition } from "@/core/engine/types";
import { useTerminalStore } from "@/core/engine/store";

export const exportCommand: CommandDefinition = {
  name: "export",
  description: "Export session history or profile to clipboard",
  usage: "export [session|resume|contact]",
  execute: async (ctx) => {
    const target = (ctx.args[0] ?? "session").toLowerCase();

    if (target === "session") {
      const history = useTerminalStore.getState().history;

      if (history.length === 0) {
        ctx.pushLine({
          type: "output",
          content: "  (no session history to export)",
          color: "#5a5a72",
        });
        return;
      }

      const text = [
        "# 0xNULL Terminal Session Export",
        `# Date: ${new Date().toISOString()}`,
        `# Commands: ${history.length}`,
        "",
        ...history.map((cmd, i) => `${String(i + 1).padStart(4)}  ${cmd}`),
        "",
      ].join("\n");

      try {
        await navigator.clipboard.writeText(text);
        ctx.pushLine({
          type: "success",
          content: `  ✔ Session history (${history.length} commands) copied to clipboard!`,
        });
      } catch {
        ctx.pushLine({
          type: "error",
          content: "  Failed to copy to clipboard. Check browser permissions.",
        });
      }
      return;
    }

    if (target === "resume") {
      const resume = [
        "═══════════════════════════════════════════",
        "  OPERATOR PROFILE — 0xNULL",
        "═══════════════════════════════════════════",
        "",
        "Designation: Senior Fullstack Architect",
        "Clearance:   Level 5 — Creative Engineering",
        "Status:      ACTIVE",
        "",
        "── SPECIALIZATIONS ──────────────────────",
        "• Fullstack Architecture (React, Node, Cloud)",
        "• 3D Web Experiences (Three.js, WebGL, WebGPU)",
        "• System Design & Distributed Systems",
        "• Creative Development & Generative Art",
        "",
        "── TECHNICAL PROFICIENCY ────────────────",
        "TypeScript      ██████████ 100%",
        "React/Next.js   █████████░  90%",
        "Three.js/WebGL  ████████░░  80%",
        "Node.js         █████████░  90%",
        "Rust/WASM       ███████░░░  70%",
        "Python          ████████░░  80%",
        "PostgreSQL      ████████░░  80%",
        "Docker/K8s      ███████░░░  70%",
        "AWS/GCP         ████████░░  80%",
        "System Design   █████████░  90%",
        "",
        "── CONTACT ─────────────────────────────",
        "Email:  alexrusu795@gmail.com",
        "GitHub: github.com/alexandru-rusuu",
        "",
        "Generated by 0xNULL Terminal Portfolio",
      ].join("\n");

      try {
        await navigator.clipboard.writeText(resume);
        ctx.pushLine({
          type: "success",
          content: "  ✔ Full resume profile copied to clipboard!",
        });
      } catch {
        ctx.pushLine({
          type: "error",
          content: "  Failed to copy to clipboard. Check browser permissions.",
        });
      }
      return;
    }

    if (target === "contact") {
      const contact = [
        "Email:  alexrusu795@gmail.com",
        "GitHub: https://github.com/alexandru-rusuu",
      ].join("\n");

      try {
        await navigator.clipboard.writeText(contact);
        ctx.pushLine({
          type: "success",
          content: "  ✔ Contact info copied to clipboard!",
        });
      } catch {
        ctx.pushLine({
          type: "error",
          content: "  Failed to copy to clipboard. Check browser permissions.",
        });
      }
      return;
    }

    ctx.pushLines([
      { type: "blank", content: "" },
      { type: "system", content: "  Usage: export <target>" },
      { type: "blank", content: "" },
      { type: "output", content: "  Targets:", color: "#00f0ff" },
      { type: "output", content: "    session    Export command history to clipboard" },
      { type: "output", content: "    resume     Export full profile to clipboard" },
      { type: "output", content: "    contact    Export contact info to clipboard" },
      { type: "blank", content: "" },
    ]);
  },
};
